# 项目信息
site_name: KAI Wiki
site_description: KAI Wiki 是一个开源的机器人竞赛知识库，提供机器人竞赛的相关知识、技术、经验等内容，帮助广大机器人竞赛爱好者更快更深入地学习机器人竞赛知识。
site_author: KAI Wiki Contributors
site_url: https://wiki.shukai.dev
strict: false

# 仓库信息
repo_name: shukai-dev/wiki.shukai.dev
repo_url: https://github.com/shukai-dev/wiki.shukai.dev
# edit_uri: todo

# 版权信息
copyright: 'Copyright &copy; 2023 KAI Wiki Team'

# 内容配置
nav: 
  - 简介: index.md
  - 学习路线: learning-path.md
  - 基础:
    - 计算机基础知识:
      - 简介: basic/cs-basic/beginning.md
    - Windows下VScode配置: basic/cs-basic/how_to_VSCode.md
    - C语言简单入门: 
      - C语言的引入: basic/cs-basic/C_language_01_frist.md
  - SBC:
    - Linux 基础知识:
      - 简介: sbc/linux-basic/beginning.md
  - 睿抗机器人开发者大赛:
    - 火线速递:
      - 简单介绍: robotcom/Hxsd/ReadMe.md
    - 智慧果园:
      - 简单介绍: robotcom/Smart_fruit/ReadMe.md
    - 物资运输:
      - 简单介绍: robotcom/Dog/ReadMe.md
      - A1:
        - 初次使用: robotcom/Dog/A1/firstusing.md
      - Go1:
        - 初次使用: robotcom/Dog/Go1/firstusing.md
    - 足球机器人:
      - 简单介绍: robotcom/FootBall/ReadMe.md

# 主题配置
theme:
  name: material
  language: 'zh'
